### ISSUE TITLE
Python3 compatability

### ISSUE THREAD

**Issue by justinvasel** [justinvasel/WHIPS#164]
WHIPS is currently designed to be used with Python 2.7, but will not work with Python 3. We should amend this.

The most obvious change that I'm aware of comes in the form of print functions. Python 3 requires the form `print("")`, but Python 2.7 also allows for `print ""`, and many of the print statements in WHIPS are of this form. They will need to be converted.

Beyond that, there are likely other subtle things that need to change. For example, I have not been able to get the build process to complete properly when I set up my virtual environment with python 3. I haven't investigated why that is, but something there will need to be fixed as well.

**Comment by matthewfeickert** [comment]
@justinvasel Something that will inform the latter parts of PR #170 is if you want to just add Python 3 compatibility or if you additionally want to **switch** to Python 3 and drop support for Python 2.7.

I will do whatever you want, but I am a strong proponent of putting Python 2.7 out to pasture &mdash; it has earned it after many more years of service then was ever intended &mdash; and having to worry about keeping things running across two versions of the software seems like an unnecessary headache.

**Comment by justinvasel** [comment]
I am entirely supportive of thanking Python 2.7 for its service and switching exclusively to Python 3.
