### ISSUE TITLE
Returning to https://www.uec-whips.org/congress/members/all resets sort to name.

### ISSUE THREAD

**Issue by adammoren** [justinvasel/WHIPS#180]
It should remember your previous sort upon returning (via the back button) to the https://www.uec-whips.org/congress/members/all page.  For example, sorting by state, then checking out the senators page, then returning to the members page and they are again sorted by name not state.  Ideally it would return to your scroll position too.

**Comment by justinvasel** [comment]
We use an third-party library for the data table functionality, so implementing this might be easier said than done, but we can look into possible solutions.

**Comment by justinvasel** [comment]
This was actually an incredibly easy fix. Thanks for suggesting it!
