### ISSUE TITLE
Make the code of conduct link more prominent on the WHIPs home page and on a primary's landing page.

### ISSUE THREAD

**Issue by bnord** [justinvasel/WHIPS#208]

**Comment by justinvasel** [comment]
Added a link to the dropdown menu under the "profile" link to make it easier to find.

![Screen Shot 2019-03-11 at 11 18 43](https://user-images.githubusercontent.com/3528936/54135721-b9354980-43f0-11e9-9457-9fdf425f3671.png)

If you have specific suggestions, let me know.
